<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Shashwats-Laptop" failures="2" tests="2" name="Default test" time="3.307" errors="0" timestamp="2020-12-21T23:11:27 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.285">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at utilities.FunctionalUtilities.getDriver(FunctionalUtilities.java:27)
at utilities.FunctionalUtilities.hitUrl(FunctionalUtilities.java:65)
at stepDefinitions.StepDefs.we_have_to_go_the_the_url_of_aut(StepDefs.java:16)
at ✽.We have to go the the url of AUT(file:///D:/git/PHPTravels-Selenium-TestNG-Framework/PHPTravels/src/test/java/features/front-end.feature:4)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.285">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at utilities.FunctionalUtilities.getDriver(FunctionalUtilities.java:27)
at utilities.FunctionalUtilities.hitUrl(FunctionalUtilities.java:65)
at stepDefinitions.StepDefs.we_have_to_go_the_the_url_of_aut(StepDefs.java:16)
at ✽.We have to go the the url of AUT(file:///D:/git/PHPTravels-Selenium-TestNG-Framework/PHPTravels/src/test/java/features/front-end1.feature:4)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
